[env:seeed_xiao_esp32c3]
platform = espressif32@6.12.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_protocol = esp-builtin
extra_scripts =
    pre:configure_toolchain.py
    post:configure_upload.py
platform_packages =
    toolchain-riscv32-esp@symlink://${PROJECT_DIR}/.toolchains/gcc8-arm64
    tool-openocd-esp32@symlink://${PROJECT_DIR}/.toolchains/openocd-arm64
lib_deps =
    https://github.com/Seeed-Studio/Seeed_GFX.git#a2de1abca0597c202193f22d01e9fa35d1ff613b
    https://github.com/bitbank2/PNGdec.git#981eeb5443b95b6d3efe88c640c1fbe061936722
build_flags =
    -I include
    -I src
    -march=rv32imc
    -DCORE_DEBUG_LEVEL=0
